### ISSUE TITLE
Add new /web-deployment and /ai-ml-deployment metadata & pages

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console-old#112]
Community Bounty: $50 (paid in $AKT)

**GOAL/ UX:**
To complete the work that https://github.com/akash-network/console/issues/100 started, we need to do the following:
- When the user clicks "Host a Web Service" we show them a page with the following tiles + "import" option:
   - Fun & Games (we already have icons and metadata for this in /nodes - just need to move it here)
   - Wordpress (need icon and metadata for this SDL: https://github.com/akash-network/awesome-akash/blob/master/wordpress/deploy.yaml)
   - Confluence https://github.com/akash-network/awesome-akash/blob/master/confluence/deploy.yaml
   - Drupal https://github.com/akash-network/awesome-akash/blob/master/drupal/deploy.yaml
   - MySQL (need icon and metadata for this SDL https://github.com/akash-network/awesome-akash/tree/master/MySQL)
   - Postgres (need icon and metadata for this SDL: https://github.com/akash-network/awesome-akash/blob/master/postgres/deploy.yaml)
   - MongoDB (need icon and metadata for this SDL: https://github.com/akash-network/awesome-akash/tree/master/mongoDB)
   - Redis (need icon and metadata for this SDL: https://github.com/akash-network/awesome-akash/blob/master/redis/deploy.yaml)
   - InfluxDB (need icon and metadata for this SDL: https://github.com/akash-network/awesome-akash/blob/master/influxdb/deploy.yaml)
   - CouchDB (need icon and metadata for this SDL https://github.com/akash-network/awesome-akash/blob/master/couchdb/deploy.yaml)
   - Jenkins (need icon and metadata for this SDL: https://github.com/akash-network/awesome-akash/blob/master/jenkins/deploy.yaml)
   - JIRA (need icon and metadata for this SDL: https://github.com/akash-network/awesome-akash/blob/master/jira/deploy.yaml)
   - HashiCorp Vault (need icon and metadata for this SDL:  https://github.com/akash-network/awesome-akash/blob/master/hashicorp-vault/deploy.yaml)

![Screenshot 2023-04-19 at 9 50 22 AM](https://user-images.githubusercontent.com/19495789/233145449-40f773e7-56f2-438f-a7f6-8cf5411aaafb.png)

  
- When the user clicks "Host an AI/ ML Model" we show them a page with the following tiles + "import" option:
   - Stable Diffusion (Easy Diffuasion UI) (need icon and metadata for this SDL: https://github.com/akash-network/awesome-akash/blob/master/stable-diffusion-ui/deploy.yaml)
   - Alpaca (need icon and metadata for this SDL: https://github.com/akash-network/awesome-akash/blob/master/alpaca-cpp/deploy.yaml)
   - Serge App (need icon and metadata for this SDL: https://github.com/akash-network/awesome-akash/blob/master/serge/deploy.yaml)
   - Jupyter Notebook (need icon and metadata for this SDL: https://github.com/akash-network/awesome-akash/blob/master/jupyter/deploy.yaml)

![Screenshot 2023-04-19 at 9 50 34 AM](https://user-images.githubusercontent.com/19495789/233145505-a54dc6c6-b304-4f9f-9b28-fc222dccc062.png)

**TASKS:*

*
- [x] Add new icons for tiles we want to see under /web-deployment in https://github.com/akash-network/deploy-templates
       -  Should go under /template-icons/web/56by56 and /template-icons/web/80by80
- [x] Add new icons for tiles we want to see under /ai-ml-deployment in https://github.com/akash-network/deploy-templates
       -  Should go under /template-icons/ai-ml/56by56 and /template-icons/ai-ml/80by80
- [x] Add new templates for tiles we want to see under /web-deployment in https://github.com/akash-network/deploy-templates
      - ideally we should group these templates under /node, /web and /ai-ml as well but we can just put in top level folder for now, since it will break code if we moved the node icons
- [] Add new templates for tiles we want to see under /ai-ml-deployment in https://github.com/akash-network/deploy-templates. We would like to include all the SDLs under the AI" section here https://github.com/akash-network/awesome-akash
- [ ] Create new pages for web services and AI/ ML and link them from /landing as designed in https://github.com/akash-network/console/issues/100

**Comment by anilmurty** [comment]
@aktdenis - would need your help with the icons here

**Comment by anilmurty** [comment]
Thanks for the icons @aktdenis - I'll work on setting up metadata next and then this should be good to pick up for any dev

**Comment by anilmurty** [comment]
first 4 tasks addressed in https://github.com/akash-network/deploy-templates/pull/7

**Comment by sonicx180** [comment]
How long do you need on this?

**Comment by anilmurty** [comment]
I was hoping to demo it early next week at a conf

**Comment by anilmurty** [comment]
@sonicx180 - I've assigned this to you. Please post updates here so I know that progress is being made and don't re-assign to someone else :)

**Comment by anilmurty** [comment]
you may also want to coordinate with @kaushik-rishi  who is working on https://github.com/akash-network/console/pull/110 and https://github.com/akash-network/console/issues/100 which are related and may conflict with this

**Comment by sonicx180** [comment]
Alright, thanks!

**Comment by sonicx180** [comment]
Where can I find the option, "host a web service"?

**Comment by anilmurty** [comment]
check the first line of the description and reference to #100 - should be clear from that

**Comment by anilmurty** [comment]
![Screenshot 2023-04-20 at 4 02 00 PM](https://user-images.githubusercontent.com/19495789/233504576-fc32b159-2870-443c-b029-a5b23e93bb5e.png)

**Comment by anilmurty** [comment]
You will be implementing the workflow that follows the "Choose a Template" button for the two middle tiles in this video recording: https://github.com/akash-network/console/issues/100#issuecomment-1516988155

**Comment by sonicx180** [comment]
This is what I see on local host. 
![image](https://user-images.githubusercontent.com/83236320/233506909-18f486b6-50b4-4d6c-88cb-05c02ca86a0c.png)

**Comment by anilmurty** [comment]
yes, because the other issue is in progress!! 
did you read my comment above? https://github.com/akash-network/console/issues/112#issuecomment-1516671270

**Comment by sonicx180** [comment]
ah, sorry.

**Comment by kaushik-rishi** [comment]
@sonicx180 - if you want to work on top of it, you can right away just create the routes and design pages for that routes, since it has nothing to do with the new landing page.

if you still want to, you can work on top of this https://github.com/kaushik-rishi/console/tree/feat-new-landing-page , i'll help you merge changes in once my PR is merged

**Comment by anilmurty** [comment]
Thanks @kaushik-rishi 

@sonicx180 - how's it going with this? If you aren't confident, please let me know asap and I'll reassign and find something simpler for you to start with.

**Comment by sonicx180** [comment]
Sorry, it took me a long time to understand this issue. I create a page component for web deployments and ai deployments that shows https://user-images.githubusercontent.com/19495789/233145505-a54dc6c6-b304-4f9f-9b28-fc222dccc062.png for the ai page and https://user-images.githubusercontent.com/19495789/233145449-40f773e7-56f2-438f-a7f6-8cf5411aaafb.png for the web deployment page? Took me too long to understand🤣

**Comment by anilmurty** [comment]
That's correct @sonicx180 and you should pretty much be able to steal the code that exists for the current node deployments page and make changes to it.

**Comment by sonicx180** [comment]
Got it, thanks!

**Comment by anilmurty** [comment]
feel confident about taking this on or prefer working on something simpler to start @sonicx180 ?

**Comment by sonicx180** [comment]
simpler, now that  I get issues :)

**Comment by anilmurty** [comment]
hey @sonicx180 - what's the status of this effort?

**Comment by anilmurty** [comment]
hey @kaushik-rishi  - are you interested in working on this one? wanted to check with you first, before I asked others, since it is very related to #100 :)

**Comment by sonicx180** [comment]
I thought I asked for simpler issue

**Comment by anilmurty** [comment]
@ArthurEmma2 - I'm assigning this to you as well since it is very closely related to #100
